### ISSUE TITLE
Alpine Expression Error when opening selector

### ISSUE THREAD

**Issue by flxsource** [johncarter-/filament-focal-point-picker#3]
When opening up the focal point picker, I'm getting this:

```
Alpine Expression Error: Cannot read properties of null (reading 'split')

Expression: "leftPct = $event.detail.currentFocus.split(' ')[0]; topPct = $event.detail.currentFocus.split(' ')[1]"
```

This is when using the `image()` callback, which is returning a valid path.

**Comment by johncarter-** [comment]
Can you give me any more to work with? Some code, a video?

I have this and it works fine:

```php
FocalPointPicker::make('focal_point')
    ->image(fn () => 'https://unsplash.com/photos/D-GvWADT9q0/download?ixid=MnwxMjA3fDB8MXx0b3BpY3x8eGpQUjRobGtCR0F8fHx8fDJ8fDE2NTU1MzY3NjQ&force=true&w=640')
```

**Comment by vonec** [comment]
Can you update this package to support laravel 10

**Comment by johncarter-** [comment]
Assuming this is no longer an issue, if it is please give me some more details and reopen 👍
